version: "3.8"

services:
  postgres:
    container_name: postgres
    image: "postgres:13"
    restart: on-failure
    environment:
      POSTGRES_USER: postgress
      POSTGRES_PASSWORD: postgress
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - "postgres:/var/lib/postgresql/data"
    healthcheck:
      test:
        - CMD
        - pg_isready
        - "-u"
        - auth
      interval: 30s
      timeout: 30s
      retries: 3

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4

    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@inventory.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "127.0.0.1:5050:80"
      - "127.0.0.1:5051:443"

  mailhog:
    container_name: mailhog
    image: mailhog/mailhog
    ports:
      - "9025:9025"
      - "8025:8025"
    volumes:
      - mailhog:/var/lib/mailhog

  redis:
    container_name: redis_container
    image: "redis:alpine"
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --loglevel warning
    volumes:
      - "./docker-volumes/cache:/data"

  rabbitmq:
    container_name: rabbitmq_container
    image: "rabbitmq:3.13-management-alpine"
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  postgres:
  mailhog:
  redis:
  rabbitmq:
