name: API Service CI

on:
  push:
    branches:
      - main


jobs:
  inventory-api:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Action Started"
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run a one-line script
        run : echo "Hello,Api!"
      - name: Run a multi-line script
        run:  |
          echo Add other actions to build,
          echo test, and deploy your project.
      - name: List files
        run: ls ${{ github.workspace }}
      - name: Print GitHub context
        env:
          GITHUB_CONTEXT: ${{toJson(github)}}
        run: echo "$GITHUB_CONTEXT"
      - name: Action completed
        run:  echo "Action completed"

      - name: Install dependencies
        run: |
          cd api
          yarn install --frozen-lockfile

      - name: Run tests
        run: |
          cd api
          yarn test

      - name: Build
        run: |
          cd api
          yarn run build

