name: publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  push-to-registry:
    name: Push to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Extra meta information
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: askurr/mic-inventory-101
          
      - name: Build and push Email service Docker image
        run: |
          cd services/email
          docker build \
            --build-arg MAIL_DATABASE_URL=$MAIL_DATABASE_URL \
            --build-arg SMTP_HOST=$SMTP_HOST \
            --build-arg SMTP_PORT=$SMTP_PORT \
            --build-arg GOOGLE_SMTP_USER=$GOOGLE_SMTP_USER \
            --build-arg GOOGLE_SMTP_PASSWORD=$GOOGLE_SMTP_PASSWORD \
            --build-arg DEFAULT_SENDER_EMAIL=$DEFAULT_SENDER_EMAIL \
            --build-arg RABBITMQ_URL=$RABBITMQ_URL \
            -t $DOCKER_USERNAME/email:${{ steps.commit_hash.outputs.hash }} \
            .
          docker push $DOCKER_USERNAME/email:${{ steps.commit_hash.outputs.hash }}


# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main

# jobs:
#   test:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v2

#       - name: Set up Node.js
#         uses: actions/setup-node@v3
#         with:
#           node-version: '20'

#       - name: Install dependencies
#         run: yarn ci
#       - name: Run tests
#         run: yarn test

# name: Email Service CI

# on:
#   push:
#     branches:
#       - main


# jobs:
#   inventory-email:
#     runs-on: ubuntu-latest
#     steps:
#       - run: echo "Action Started"
#       - name: Checkout
#         uses: actions/checkout@v4
#       - name: Run a one-line script
#         run : echo "Hello,email!"
#       - name: Run a multi-line script
#         run:  |
#           echo Add other actions to build,
#           echo test, and deploy your project.
#       - name: List files
#         run: ls ${{ github.workspace }}
#       - name: Print GitHub context
#         env:
#           GITHUB_CONTEXT: ${{toJson(github)}}
#         run: echo "$GITHUB_CONTEXT"
#       - name: Action completed
#         run:  echo "Action completed"
