name: Build and Push Docker Images

on:
  push:
    paths:
      - 'services/product/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Get commit hash
        id: commit_hash
        run: echo "::set-output name=hash::$(git rev-parse --short HEAD)"
      
      - name: Login to Docker Hub
        run: echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

      - name: Build and push Product service Docker image
        run: |
          cd services/product
          docker build \
            --build-arg PRODUCT_DATABASE_URL="${{ secrets.PRODUCT_DATABASE_URL }}" \
            --build-arg INVENTORY_SERVICE_URL="${{ secrets.INVENTORY_SERVICE_URL }}" \
            -t $DOCKER_USERNAME/product:${{ steps.commit_hash.outputs.hash }} \
            .
          docker push $DOCKER_USERNAME/product:${{ steps.commit_hash.outputs.hash }}



# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main

# jobs:
#   test:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v2

#       - name: Set up Node.js
#         uses: actions/setup-node@v3
#         with:
#           node-version: '20'

#       - name: Install dependencies
#         run: yarn ci
#       - name: Run tests
#         run: yarn test



# on:
#   push:
#     branches:
#       - main


# jobs:
#   inventory-product:
#     runs-on: ubuntu-latest
#     steps:
#       - run: echo "Action Started"
#       - name: Checkout
#         uses: actions/checkout@v4
#       - name: Run a one-line script
#         run : echo "Hello,Product!"
#       - name: Run a multi-line script
#         run:  |
#           echo Add other actions to build,
#           echo test, and deploy your project.
#       - name: List files
#         run: ls ${{ github.workspace }}
#       - name: Print GitHub context
#         env:
#           GITHUB_CONTEXT: ${{toJson(github)}}
#         run: echo "$GITHUB_CONTEXT"
#       - name: Action completed
#         run:  echo "Action completed"
